### PR TITLE
DOC: fixed wrong settings name

### PR DESCRIPTION
**Pull request by se02035**
# What we are trying to address

- Documentation contains an error (wrong settings name)

## Description of Changes

- Documentation update

## Other information or known dependencies

- Using the wrong setting (name) the python extension won't work

### CODE REVIEW

**Review by lzchen — APPROVED** [review]

**Review by Hazhzeng — APPROVED** [review]

**Comment by lzchen** [comment]
@se02035 
Please sign the CLA then we can merge your PR :)

**Comment by se02035** [comment]
Already signed (last Saturday)
________________________________

**Comment by lzchen** [comment]
@se02035 
Can you reply with `@googlebot I signed it!` so we can verify.

**Comment by se02035** [comment]
@googlebot I fixed it.

**Comment by se02035** [comment]
@googlebot I fixed it.

**Pull request merged**
